### ISSUE TITLE
Measurement 4: old download link for the cifar_resnet110.th?

### ISSUE THREAD

**Issue by aitrain** [princetonvisualai/revise-tool#12]
Hello,

I think the download bash script should be updated. 
Using the current script caused the error: __pickle.UnpicklingError: invalid load key, '<'._

By manually downloading from [this link](https://github.com/akamaster/pytorch_resnet_cifar10/blob/master/pretrained_models/resnet110-1d1ed7c2.th) rather than the one from [download.sh](https://github.com/akamaster/pytorch_resnet_cifar10/raw/master/pretrained_models/resnet110-1d1ed7c2.th) I resolved the error. 

Just as a tip for future users. :) 

Thank you very much for providing this tool. 

Best regards,
Nastassia

**Comment by Angelina-Wang** [comment]
Hmm I didn't run into this when I downloaded, but it may just be a difference in python versions, thanks for noting!
