### ISSUE TITLE
Gender Labeling

### ISSUE THREAD

**Issue by aitrain** [princetonvisualai/revise-tool#14]
Hi, 
it's me again. 

Just as a quick tip for other users/you. :) 
In `datasets.py` you stated in the `TemplateDataset` in the method `from_path`:

`gender = None # optional, we have used 0 for female and 1 for male when these labels exist`

So, I followed the instruction and have set: 
`if gender == "Female":
        binary_gender = 0
 if gender == "Male":
            binary_gender = 1`

I calculated the number of Male and Female persons depicted in the images beforehand, so I know how many of them there are. Unfortunately the number for Male and Female persons is exactly switched in the first measurement (M0) which leads me into believing that you used 
```
0:Male

1:Female 
```
labeling instead.

No critique, just a friendly tip for you/your future users. Since running the measurement 1 took a bit more than two hours for me and now I will rerun it, I want to prevent this for your users. :)

All the best to you and best regards,
Nastassia

**Comment by Angelina-Wang** [comment]
Hi Nastassia, good catch! Thank you very much for bringing this up, it has been fixed :)
