### ISSUE TITLE
Difference between person_center and ann_center? 

### ISSUE THREAD

**Issue by aitrain** [princetonvisualai/revise-tool#15]
Hi,

I have a short question regarding the bounding boxes. In measurement 3 (M3) you use bounding boxes from gender and from anns. However, I don't quite understand the difference between those. 
In my understanding, gender is passed the person bounding box. But which bounding box is passed to anns? 

Thank you very much in advance.

All the best,
Nastassia

**Comment by Angelina-Wang** [comment]
Hi Nastassia, the bounding boxes in anns correspond to objects, whereas the bounding boxes passed through gender corresponds to the person. If there are no objects in your dataset, anns can be left as an empty list. Hope that helps!
