### ISSUE TITLE
Two types of bounding boxes?

### ISSUE THREAD

**Issue by aitrain** [princetonvisualai/revise-tool#16]
Hi,

I have a short question regarding the bounding boxes. In measurement 3 (M3) you use bounding boxes from gender and from anns. However, I don't quite understand the difference between those. 
In my understanding, gender is passed the person bounding box. But which bounding box is passed to anns? 

Thank you very much in advance.

All the best,
Nastassia

**Comment by Angelina-Wang** [comment]
repeat question to issue #15
