### ISSUE TITLE
Dataset Reference for COCO

### ISSUE THREAD

**Issue by drishyamlabs** [princetonvisualai/revise-tool#2]
Hi,

First of all thanks a lot for releasing wonderful tool. Kudos.
I am struggling with running the tool properly on COCO dataset as this seems to be a missing link- 

**gender_data = pickle.load(open('Data/Coco/2014data/bias_splits/train.data', 'rb'))**

Also, I am not able to understand what is happening in the next line:

**self.gender_info = {int(chunk['img'][15:27]): chunk['annotation'][0] for chunk in gender_data}**

Can you please guide me with the path to download this pickle file which is acceptable by the code.

**Comment by Angelina-Wang** [comment]
yes good point my bad! The gender annotations come from a previous work, [Men Also Like Shopping](https://arxiv.org/abs/1707.09457), and those data files are located [here](https://github.com/uclanlp/reducingbias/tree/master/data/COCO)!
