### ISSUE TITLE
M1 distance calculation

### ISSUE THREAD

**Issue by aitrain** [princetonvisualai/revise-tool#25]
Hi Angelina,

sorry, it's me again! 
I have a short question regarding M1. You compute the distance from the person to the image center as:
`distance = np.linalg.norm(person_center - img_center)`
However, you set:
` img_center = np.array([.5, .5])`

Maybe I am wrong, but did you maybe forget to multiply with the image size itself? Since the person_center is given in pixel values.

Please correct me if I am wrong, I was just wondering. :)

Thanks so much,
Nastassia

**Comment by Angelina-Wang** [comment]
Hi Nastassia, sorry if there was a confusion! Actually, person_center should be scaled so that all values are between 0 and 1. A comment has been added to datasets.py to reflect this.
