### ISSUE TITLE
Question about Hierarchy Plot

### ISSUE THREAD

**Issue by aitrain** [princetonvisualai/revise-tool#29]
Hi Angelina, 

just a quick question. How should the hierarchy visualization be interpreted? 

Thank you very much in advance! :)

All the best,
Nastassia

**Comment by Angelina-Wang** [comment]
They serve as a sanity check on if the co-occurrences are aligned with your mental model. For example, in a dataset if forks and spoons co-occur frequently, this is probably what you would expect, but if forks and soccer balls also co-occur just as frequently, this may lead to a different understanding of what kinds of images the dataset contain (maybe more outdoor eating scenes than indoor ones)
