### ISSUE TITLE
Not able to download coco datasets

### ISSUE THREAD

**Issue by SaiAparna1** [princetonvisualai/revise-tool#5]
I am getting following error while loading coco dataset,
**FileNotFoundError:** [Errno 2] No such file or directory: 'Data/Coco/2014data/annotations/instances_train2014.json'
can anyone please provide the link to download above files?

Thanks in advance.

**Comment by Angelina-Wang** [comment]
Yes, the link to download COCO dataset is [here](https://cocodataset.org/#download), and the specific json you listed is "2014 Train/Val annotations [241MB]"
