### ISSUE TITLE
How to use RESIVE on my own dataset？

### ISSUE THREAD

**Issue by Masterzhuior** [princetonvisualai/revise-tool#55]
I want to use it to check the bias of my training data（face dataset）. Do I need to preprocess the dataset with some annotators in advance ?

**Comment by Angelina-Wang** [comment]
Hello! Yes, given that the annotation-free analyses, e.g., scene recognition, are probably not very relevant on a face dataset, you would get the most out of the tool if the images had annotations associated with them.
